# Generated by Django 3.1.3 on 2020-11-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Houses')),
                ('address', models.CharField(max_length=100)),
                ('sqft', models.FloatField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('cp', models.PositiveIntegerField(null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title', '-created'],
            },
        ),
    ]
