# Generated by Django 3.1.3 on 2020-11-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproperties',
            name='proprety_status',
            field=models.CharField(choices=[('for sale', 'For Sale'), ('for rent', 'For Rent')], default='For Sale', max_length=200),
        ),
        migrations.AddField(
            model_name='featuredproperties',
            name='proprety_type',
            field=models.CharField(choices=[('appartment', 'Appartment'), ('house', 'House'), ('commercial', 'Commercial')], default='Appartment', max_length=200),
        ),
    ]
