# Generated by Django 3.1.3 on 2020-11-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20201127_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproperties',
            name='city',
            field=models.CharField(choices=[('par', 'Paris'), ('mar', 'Marseille'), ('brd', 'Bordeaux'), ('tls', 'Toulouse'), ('sta', 'Strasbourg'), ('nnt', 'Nantes'), ('ln', 'Lyon'), ('mp', 'Montpellier')], default='City', max_length=200),
        ),
    ]
