# Generated by Django 3.1.3 on 2020-11-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20201127_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproperties',
            name='city',
            field=models.CharField(choices=[('Paris', 'Paris'), ('Marseille', 'Marseille'), ('Bordeaux', 'Bordeaux'), ('Toulouse', 'Toulouse'), ('Strasbourg', 'Strasbourg'), ('Nantes', 'Nantes'), ('lyon', 'Lyon'), ('Montpellier', 'Montpellier')], default='City', max_length=200),
        ),
    ]
