# Generated by Django 3.1.3 on 2020-11-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20201127_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredproperties',
            old_name='proprety_type',
            new_name='proprety_types',
        ),
    ]
