# Generated by Django 3.1.3 on 2020-11-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20201127_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredproperties',
            old_name='proprety_status',
            new_name='property_status',
        ),
    ]
