# Generated by Django 3.1.3 on 2020-11-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_auto_20201127_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproperties',
            name='property_status',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=200),
        ),
    ]
