# Generated by Django 3.1.3 on 2020-11-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_auto_20201127_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproperties',
            name='property_status',
            field=models.CharField(choices=[('for sale', 'For Sale'), ('for rent', 'For Rent')], default='For Sale', max_length=200),
        ),
    ]
