# Generated by Django 3.1.3 on 2020-11-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_auto_20201127_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproperties',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
