# Generated by Django 3.1.3 on 2020-11-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_featuredproperties_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproperties',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
