# Generated by Django 3.1.3 on 2020-12-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_auto_20201129_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredproperties',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='featuredproperties',
            name='owner',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
