# Generated by Django 3.1.3 on 2020-12-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_auto_20201201_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproperties',
            name='balcony',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='featuredproperties',
            name='terrasse',
            field=models.BooleanField(default=False),
        ),
    ]
