# Generated by Django 3.1.3 on 2020-12-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_auto_20201201_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproperties',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuredproperties',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='Houses'),
        ),
        migrations.AddField(
            model_name='featuredproperties',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Houses'),
        ),
        migrations.AddField(
            model_name='featuredproperties',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Houses'),
        ),
        migrations.AddField(
            model_name='featuredproperties',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='Houses'),
        ),
        migrations.AddField(
            model_name='featuredproperties',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='Houses'),
        ),
    ]
