# Generated by Django 3.1.3 on 2020-12-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0015_auto_20201206_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='featuredproperties',
            name='property_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.property_status'),
        ),
        migrations.AlterField(
            model_name='featuredproperties',
            name='property_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.property_types'),
        ),
    ]
