# Generated by Django 3.1.3 on 2020-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='owner',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
