# Generated by Django 3.1.3 on 2020-11-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0002_properties_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_status',
            field=models.CharField(choices=[('for sale', 'For Sale'), ('for rent', 'For Rent')], default='For Sale', max_length=200),
        ),
        migrations.AddField(
            model_name='properties',
            name='property_types',
            field=models.CharField(choices=[('appartment', 'Appartment'), ('house', 'House'), ('commercial', 'Commercial')], default='Appartment', max_length=200),
        ),
    ]
