# Generated by Django 3.1.3 on 2020-11-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0003_auto_20201129_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='city',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
