# Generated by Django 3.1.3 on 2020-11-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0004_properties_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='city',
            field=models.CharField(choices=[('Paris', 'Paris'), ('Marseille', 'Marseille'), ('Bordeaux', 'Bordeaux'), ('Toulouse', 'Toulouse'), ('Strasbourg', 'Strasbourg'), ('Nantes', 'Nantes'), ('lyon', 'Lyon'), ('Montpellier', 'Montpellier')], default='Appartment', max_length=200),
        ),
    ]
