# Generated by Django 3.1.3 on 2020-11-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0005_auto_20201129_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='cp',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
