# Generated by Django 3.1.3 on 2020-12-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0006_properties_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
