# Generated by Django 3.1.3 on 2020-12-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0007_auto_20201206_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
