# Generated by Django 3.1.3 on 2020-12-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propreties', '0008_properties_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
